#####
# 
# A *very low recall* list of people who have put out work similar
# to my own interests. Many great researchers missing!
# 
#####

RESEARCHERS = [
    "Albert Gu",
    "Alexander M Rush",
    "Alexander M. Rush",
    "Alexander Wettig",
    "Alisa Liu",
    "Angelica Chen",
    "Antoine Bosselut",
    "Ari Holtzman",
    "Arthur Conmy",
    "Aryaman Arora",
    "Ashton Anderson",
    "Ashwinee Panda",
    "Bill Yuchen Lin",
    "Byron C Wallace",
    "Chaitanya Malaviya",
    "Christopher D Manning",
    "Christopher Potts",
    "Clémentine Fourrier",
    "Cody Blakeney",
    "Colin Raffel",
    "Dan Jurafsky",
    "Dan Roth",
    "Daniel Khashabi",
    "Danqi Chen",
    "Daphne Ippolito",
    "David Mimno",
    "David Wadden",
    "Dawn Song",
    "Dieuwke Hupkes",
    "Diyi Yang",
    "Ethan Perez",
    "Eunsol Choi",
    "Graham Neubig",
    "Greg Durrett",
    "Hamish Ivison",
    "Hannaneh Hajishirzi",
    "He He",
    "Ian Magnusson",
    "Ian Tenney",
    "J Zico Kolter",
    "Jack Merullo",
    "Jacob Andreas",
    "Jacob Dunefsky",
    "Jacob Eisenstein",
    "Jared Kaplan",
    "Jeffrey Li",
    "Jesse Dodge",
    "John Hewitt",
    "John Xavier Morris",
    "John Yang",
    "Jonathan Hayase",
    "Josh Gardner",
    "Julia Hockenmaier",
    "Karthik R Narasimhan",
    "Kilian Q Weinberger",
    "Kyle Lo",
    "Kyunghyun Cho",
    "Lillian Lee",
    "Luca Soldaini",
    "Ludwig Schmidt",
    "Luke Zettlemoyer",
    "Maarten Sap",
    "Matthew Finlayson",
    "Michael J. Ryan",
    "Mike Lewis",
    "Miriam Wanner",
    "Mitchell Wortsman",
    "Mohit Iyyer",
    "Monojit Choudhury",
    "Neel Nanda",
    "Nelson F. Liu",
    "Niklas Muennighoff",
    "Noah A. Smith",
    "Noah Goodman",
    "Omer Levy",
    "Orion Weller",
    "Pang Wei Koh",
    "Patrick Fernandes",
    "Percy Liang",
    "Peter West",
    "Rafael Rafailov",
    "Raj Sanjay Shah",
    "Roger Grosse",
    "Ronan Le Bras",
    "Rose Hendrix",
    "Ryan Cotterell",
    "Samir Yitzhak Gadre",
    "Sanmi Koyejo",
    "Sashank Varma",
    "Scott Geng",
    "Sean J Welleck",
    "Sean Welleck",
    "Seungone Kim",
    "sewoong oh",
    "Sham M Kakade",
    "Sherry Yang",
    "Shuyue Stella Li",
    "Siva Reddy",
    "Stefano Ermon",
    "Swabha Swayamdipta",
    "Swaroop Mishra",
    "Tanya Goyal",
    "Tatsunori Hashimoto",
    "Taylor Berg-Kirkpatrick",
    "Trevor Darrell",
    "Tri Dao",
    "Valentina Pyatkin",
    "Victoria Graf",
    "Wei Xu",
    "William Held",
    "William Merrill",
    "William Yang Wang",
    "Xiang Lisa Li",
    "Yao Dou",
    "Yapei Chang",
    "Yejin Choi",
    "Yoav Artzi",
    "Yu Wu (吴俣)",
    "Yulia Tsvetkov",
    "Zhenda Xie（解振达）",
    "Zijun Liu",
]
