#####
# 
# A *very low recall* list of people who have put out work similar
# to my own interests. Many great researchers missing!
# 
#####

ARXIV_RESEARCHERS = [
    "Albert Gu",
    "Alexander M Rush",
    "Alexander M. Rush",
    "Alexander Wettig",
    "Antoine Bosselut",
    "Ari Holtzman",
    "Ashwinee Panda",
    "Christopher D Manning",
    "Christopher Potts",
    "Christopher Ré",
    "Clémentine Fourrier",
    "Colin Raffel",
    "Dan Jurafsky",
    "Danqi Chen",
    "David Wadden",
    "Diyi Yang",
    "Ethan Perez",
    "Eunsol Choi",
    "Graham Neubig",
    "Greg Durrett",
    "Hamish Ivison",
    "Hannaneh Hajishirzi",
    "Ian Magnusson",
    "J Zico Kolter",
    "Jack Merullo",
    "Jacob Andreas",
    "Jacob Eisenstein",
    "Jared Kaplan",
    "Jesse Dodge",
    "John Hewitt",
    "John Xavier Morris",
    "Karthik R Narasimhan",
    "Kyle Lo",
    "Lillian Lee",
    "Luca Soldaini",
    "Ludwig Schmidt",
    "Luke Zettlemoyer",
    "Maarten Sap",
    "Mike Lewis",
    "Neel Nanda",
    "Nelson F. Liu",
    "Niklas Muennighoff",
    "Noah A. Smith",
    "Noah Goodman",
    "Orion Weller",
    "Pang Wei Koh",
    "Percy Liang",
    "Rafael Rafailov",
    "Samir Yitzhak Gadre",
    "Sanmi Koyejo",
    "Sean J Welleck",
    "Sean Welleck",
    "Seungone Kim",
    "Tanya Goyal",
    "Tri Dao",
    "William Held",
    "Xiang Lisa Li",
    "Yejin Choi",
    "Yoav Artzi",
]

RESEARCHERS = ARXIV_RESEARCHERS + [
    "Alisa Liu",
    "Angelica Chen",
    "Arthur Conmy",
    "Aryaman Arora",
    "Ashton Anderson",
    "Bill Yuchen Lin",
    "Byron C Wallace",
    "Chaitanya Malaviya",
    "Cody Blakeney",
    "Dan Roth",
    "Daniel Khashabi",
    "Daphne Ippolito",
    "David Mimno",
    "Dawn Song",
    "Dieuwke Hupkes",
    "He He",
    "Ian Tenney",
    "Jacob Dunefsky",
    "Jeffrey Li",
    "John Yang",
    "Jonathan Hayase",
    "Josh Gardner",
    "Julia Hockenmaier",
    "Kilian Q Weinberger",
    "Kyunghyun Cho",
    "Matthew Finlayson",
    "Michael J. Ryan",
    "Miriam Wanner",
    "Mitchell Wortsman",
    "Mohit Iyyer",
    "Monojit Choudhury",
    "Omer Levy",
    "Patrick Fernandes",
    "Peter West",
    "Raj Sanjay Shah",
    "Roger Grosse",
    "Ronan Le Bras",
    "Rose Hendrix",
    "Ryan Cotterell",
    "Sashank Varma",
    "Scott Geng",
    "sewoong oh",
    "Sham M Kakade",
    "Sherry Yang",
    "Shuyue Stella Li",
    "Siva Reddy",
    "Stefano Ermon",
    "Swabha Swayamdipta",
    "Swaroop Mishra",
    "Tatsunori Hashimoto",
    "Taylor Berg-Kirkpatrick",
    "Trevor Darrell",
    "Valentina Pyatkin",
    "Victoria Graf",
    "Wei Xu",
    "William Merrill",
    "William Yang Wang",
    "Yao Dou",
    "Yapei Chang",
    "Yu Wu (吴俣)",
    "Yulia Tsvetkov",
    "Zhenda Xie（解振达）",
    "Zijun Liu",
]
